name: CD - PyPi - Release - Development

on:
  push:
    tags:
      - "v*.*.*-dev"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          # either build for 11 or latest 12? unit tests will cover compatibility
          # and whl is installable in all python 3 versions
          python-version: "3.11"

      - name: Install Hatch
        run: pip install hatch

      - name: Install dependencies
        run: pip install .

      - name: Build the package
        run: hatch build

      - name: Publish to PyPI
        env:
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_TEST_TOKEN}}
        run: hatch --repo test publish
