# Workflow to deploy to pypi
#
# Just using manual deployments as pypi denies overwriting pkg versions,
# Please increment the semantic version with one of `poetry version [major,minor,patch,dev,post]`
# and commit to branch before running

name: CD - Release - Production

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Get Version
        run: |
          echo "BUILD_VERSION=$(hatch version)" >> $GITHUB_ENV

      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          verbose: true

      - name: Echo Package Info
        run: |
          echo "Package version $BUILD_VERSION published to PyPI"
          echo "Install with: pip install eratos-sdk==$BUILD_VERSION"
