# workflow to deploy to test pypi

name: CD - Release - Development

# Just using manual deployments as pypi denies overwriting pkg versions,
# Please increment the semantic version with one of `poetry version [major,minor,patch,dev,post]`
# and commit to branch before running
on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Get Version
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "BUILD_VERSION=$(poetry version | awk '{print $2}')"  >> $GITHUB_ENV

      - name: Build package
        run: poetry build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist/
          verbose: true

      - name: Echo Package Info
        run: |
          echo "Package version $BUILD_VERSION published to PyPI"
          echo "Install with: pip install --index-url https://test.pypi.org/simple/ eratos-sdk==$BUILD_VERSION"
